<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Cleaning Completion Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 14px; color: #333; line-height: 1.6; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        h1 { color: #1f2937; font-size: 24px; margin-bottom: 20px; }
        .summary { background: #f3f4f6; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
        .summary p { margin: 5px 0; }
        .summary strong { color: #1f2937; }
        .stats { display: flex; gap: 20px; margin-bottom: 20px; }
        .stat-box { flex: 1; background: #e0e7ff; padding: 15px; border-radius: 8px; text-align: center; }
        .stat-value { font-size: 24px; font-weight: bold; color: #4f46e5; }
        .stat-label { color: #6366f1; font-size: 12px; }
        .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Cleaning Completion Report</h1>
        
        <div class="summary">
            <p><strong>Property:</strong> {{ $session->property->name }}</p>
            <p><strong>Address:</strong> {{ $session->property->address }}</p>
            <p><strong>Housekeeper:</strong> {{ $session->housekeeper->name }}</p>
            <p><strong>Date:</strong> {{ $session->scheduled_date->format('F d, Y') }}</p>
            <p><strong>Status:</strong> {{ ucfirst($session->status) }}</p>
        </div>

        <table style="width: 100%; border-collapse: separate; border-spacing: 10px 0;">
            <tr>
                <td style="background: #e0e7ff; padding: 15px; border-radius: 8px; text-align: center;">
                    <div style="font-size: 24px; font-weight: bold; color: #4f46e5;">{{ $completionRate }}%</div>
                    <div style="color: #6366f1; font-size: 12px;">Completion Rate</div>
                </td>
                <td style="background: #d1fae5; padding: 15px; border-radius: 8px; text-align: center;">
                    <div style="font-size: 24px; font-weight: bold; color: #059669;">{{ $completedTasks }}/{{ $totalTasks }}</div>
                    <div style="color: #10b981; font-size: 12px;">Tasks Completed</div>
                </td>
                <td style="background: #fef3c7; padding: 15px; border-radius: 8px; text-align: center;">
                    <div style="font-size: 24px; font-weight: bold; color: #d97706;">{{ $duration ?? '—' }}</div>
                    <div style="color: #f59e0b; font-size: 12px;">Duration</div>
                </td>
            </tr>
        </table>

        <p style="margin-top: 20px;">Please find the detailed PDF report attached to this email.</p>

        <div class="footer">
            <p>This email was automatically generated by the HK Checklist System.</p>
            <p>© {{ date('Y') }} All rights reserved.</p>
        </div>
    </div>
</body>
</html>
